SHAPES = (
    ('box', "Box"),
    ('ellipse', "Ellipse"),
    ('oval', "Oval"),
    ('circle', "Circle"),
    ('point', "Point"),
    ('egg', "Egg"),
    ('triangle', "Triangle"),
    ('diamond', "Diamond"),
    ('trapezium', "Trapezium"),
    ('parallelogram', "Parallelogram"),
    ('house', "House"),
    ('pentagon', "Pentagon"),
    ('hexagon', "Hexagon"),
    ('septagon', "Septagon"),
    ('octagon', "Octagon"),
    ('doublecircle', "Double Circle"),
    ('doubleoctagon', "Double Octagon"),
    ('tripleoctagon', "Triple Octagon"),
    ('invtriangle', "Inverted Triangle"),
    ('invtrapezium', "Inverted Trapezium"),
    ('invhouse', "Inverted House"),
    ('Mdiamond', "Fancy Diamond"),
    ('Msquare', "Fancy Square"),
    ('Mcircle', "Fancy Circle"),
    ('rectangle', "Rectangle"),
    ('square', "Square"),
    ('star', "Star"),
    ('cylinder', "Cylinder"),
    ('note', "Note"),
    ('tab', "Tab"),
    ('folder', "Folder"),
    ('box3d', "3D Box"),
)

COLORS = (
    ('white', "White"),
    ('gray', "Gray"),
    ('red', "Red"),
    ('orange', "Orange"),
    ('yellow', "Yellow"),
    ('green', "Green"),
    ('cyan', "Cyan"),
    ('violet', "Violet"),
    ('beige', "Beige"),
    ('plum', "Plum"),
    ('salmon', "Salmon"),
    ('turquiose', "Turquoise"),
    ('goldenrod', "Goldenrod"),
    ('firebrick', "Firebrick"),
    ('chocolate', "Chocolate"),
    ('steelblue', "Steel Blue"),
    ('springgreen', "Spring Green"),
)
