# Generated by Django 2.2.2 on 2019-06-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("mapping", "0002_auto_20190619_1752")]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="mapping.Workspace",
            ),
        )
    ]
