# Generated by Django 2.2.2 on 2019-06-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_auto_20190619_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
