# Generated by Django 2.2.2 on 2019-06-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_workspace_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemtype',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
