# Generated by Django 2.2.2 on 2019-06-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("mapping", "0009_auto_20190620_1423")]

    operations = [migrations.RemoveField(model_name="item", name="dependencies")]
