# Generated by Django 2.2.2 on 2019-06-21 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("mapping", "0011_dependency_description")]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="engine",
            field=models.CharField(
                choices=[("dot", "Dot"), ("neato", "Neato")],
                default="dot",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="item1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="depends_on",
                to="mapping.Item",
            ),
        ),
        migrations.AlterField(
            model_name="dependency",
            name="item2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supports",
                to="mapping.Item",
            ),
        ),
    ]
